DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS item_requests CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE if not exists users (
  id BIGINT GENERATED by default as identity not null PRIMARY KEY,
  name varchar(200) NOT NULL,
  email varchar(200) NOT NULL,
  UNIQUE (email)
);

CREATE TABLE if not exists item_requests (
  id BIGINT GENERATED by default as identity not null PRIMARY KEY,
  description varchar(355) NOT NULL,
  requestor_id BIGINT
);

CREATE TABLE if not exists items (
  id BIGINT GENERATED by default as identity not null PRIMARY KEY,
  name varchar(200) NOT NULL,
  description varchar(355) NOT NULL,
  is_available BOOLEAN,
  owner_id BIGINT,
  request_id BIGINT
);

CREATE TABLE if not exists bookings (
  id BIGINT GENERATED by default as identity not null PRIMARY KEY,
  status varchar(8) NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE,
  end_date TIMESTAMP WITHOUT TIME ZONE,
  booker_id BIGINT,
  item_id BIGINT
);

CREATE TABLE if not exists comments (
  id BIGINT GENERATED by default as identity not null PRIMARY KEY,
  text varchar(355) NOT NULL,
  author_id BIGINT,
  item_id BIGINT,
  created TIMESTAMP WITHOUT TIME ZONE,
  UNIQUE (item_id, author_id)
);

ALTER TABLE item_requests ADD FOREIGN KEY (requestor_id) REFERENCES users (id)on delete cascade;

ALTER TABLE items ADD FOREIGN KEY (owner_id) REFERENCES users (id)on delete cascade;

ALTER TABLE items ADD FOREIGN KEY (request_id) REFERENCES item_requests (id)on delete cascade;

ALTER TABLE bookings ADD FOREIGN KEY (booker_id) REFERENCES users (id)on delete cascade;

ALTER TABLE bookings ADD FOREIGN KEY (item_id) REFERENCES items (id)on delete cascade;

ALTER TABLE comments ADD FOREIGN KEY (author_id) REFERENCES users (id)on delete cascade;

ALTER TABLE comments ADD FOREIGN KEY (item_id) REFERENCES items (id)on delete cascade;